-- ============================================================
-- openGauss migration DDL v3 - IDEMPOTENT
-- Can be executed repeatedly against a partially initialized schema.
--
-- Idempotency:
--   CREATE TABLE IF NOT EXISTS
--   CREATE [UNIQUE] INDEX IF NOT EXISTS
--   FOREIGN KEY guarded by pg_constraint existence check
--   COMMENT ON is naturally repeatable
--
-- NOTE:
--   IF an existing table was created with the wrong structure, IF NOT EXISTS
--   will NOT repair/alter that structure. This script is intended to fill
--   missing objects safely, not migrate incompatible existing definitions.
-- ============================================================

-- ==================== 1. TABLES ====================
CREATE TABLE IF NOT EXISTS gen_table (
    table_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    table_name varchar(200) DEFAULT '',
    table_comment varchar(500) DEFAULT '',
    sub_table_name varchar(64) DEFAULT NULL,
    sub_table_fk_name varchar(64) DEFAULT NULL,
    class_name varchar(100) DEFAULT '',
    tpl_category varchar(200) DEFAULT 'crud',
    tpl_web_type varchar(30) DEFAULT '',
    package_name varchar(100) DEFAULT NULL,
    module_name varchar(30) DEFAULT NULL,
    business_name varchar(30) DEFAULT NULL,
    function_name varchar(50) DEFAULT NULL,
    function_author varchar(50) DEFAULT NULL,
    gen_type char(1) DEFAULT '0',
    gen_path varchar(200) DEFAULT '/',
    options varchar(1000) DEFAULT NULL,
    create_by varchar(64) DEFAULT '',
    create_time timestamp DEFAULT NULL,
    update_by varchar(64) DEFAULT '',
    update_time timestamp DEFAULT NULL,
    remark varchar(500) DEFAULT NULL,
    PRIMARY KEY (table_id)
);

CREATE TABLE IF NOT EXISTS gen_table_column (
    column_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    table_id bigint DEFAULT NULL,
    column_name varchar(200) DEFAULT NULL,
    column_comment varchar(500) DEFAULT NULL,
    column_type varchar(100) DEFAULT NULL,
    java_type varchar(500) DEFAULT NULL,
    java_field varchar(200) DEFAULT NULL,
    is_pk char(1) DEFAULT NULL,
    is_increment char(1) DEFAULT NULL,
    is_required char(1) DEFAULT NULL,
    is_insert char(1) DEFAULT NULL,
    is_edit char(1) DEFAULT NULL,
    is_list char(1) DEFAULT NULL,
    is_query char(1) DEFAULT NULL,
    query_type varchar(200) DEFAULT 'EQ',
    html_type varchar(200) DEFAULT NULL,
    dict_type varchar(200) DEFAULT '',
    sort int DEFAULT NULL,
    create_by varchar(64) DEFAULT '',
    create_time timestamp DEFAULT NULL,
    update_by varchar(64) DEFAULT '',
    update_time timestamp DEFAULT NULL,
    PRIMARY KEY (column_id)
);

CREATE TABLE IF NOT EXISTS sys_config (
    config_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    config_name varchar(100) DEFAULT '',
    config_key varchar(100) DEFAULT '',
    config_value varchar(500) DEFAULT '',
    config_type char(1) DEFAULT 'N',
    create_by varchar(64) DEFAULT '',
    create_time timestamp DEFAULT NULL,
    update_by varchar(64) DEFAULT '',
    update_time timestamp DEFAULT NULL,
    remark varchar(500) DEFAULT NULL,
    PRIMARY KEY (config_id)
);

CREATE TABLE IF NOT EXISTS sys_dept (
    dept_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    parent_id bigint DEFAULT 0,
    ancestors varchar(50) DEFAULT '',
    dept_name varchar(30) DEFAULT '',
    order_num int DEFAULT 0,
    leader varchar(20) DEFAULT NULL,
    phone varchar(11) DEFAULT NULL,
    email varchar(50) DEFAULT NULL,
    status char(1) DEFAULT '0',
    del_flag char(1) DEFAULT '0',
    create_by varchar(64) DEFAULT '',
    create_time timestamp DEFAULT NULL,
    update_by varchar(64) DEFAULT '',
    update_time timestamp DEFAULT NULL,
    PRIMARY KEY (dept_id)
);

CREATE TABLE IF NOT EXISTS sys_dict_data (
    dict_code bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    dict_sort int DEFAULT 0,
    dict_label varchar(100) DEFAULT '',
    dict_value varchar(100) DEFAULT '',
    dict_type varchar(100) DEFAULT '',
    css_class varchar(100) DEFAULT NULL,
    list_class varchar(100) DEFAULT NULL,
    is_default char(1) DEFAULT 'N',
    status char(1) DEFAULT '0',
    create_by varchar(64) DEFAULT '',
    create_time timestamp DEFAULT NULL,
    update_by varchar(64) DEFAULT '',
    update_time timestamp DEFAULT NULL,
    remark varchar(500) DEFAULT NULL,
    PRIMARY KEY (dict_code)
);

CREATE TABLE IF NOT EXISTS sys_dict_type (
    dict_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    dict_name varchar(100) DEFAULT '',
    dict_type varchar(100) DEFAULT '',
    status char(1) DEFAULT '0',
    create_by varchar(64) DEFAULT '',
    create_time timestamp DEFAULT NULL,
    update_by varchar(64) DEFAULT '',
    update_time timestamp DEFAULT NULL,
    remark varchar(500) DEFAULT NULL,
    PRIMARY KEY (dict_id)
);

CREATE TABLE IF NOT EXISTS sys_job (
    job_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    job_name varchar(64) NOT NULL DEFAULT '',
    job_group varchar(64) NOT NULL DEFAULT 'DEFAULT',
    invoke_target varchar(500) NOT NULL,
    cron_expression varchar(255) DEFAULT '',
    misfire_policy varchar(20) DEFAULT '3',
    concurrent char(1) DEFAULT '1',
    status char(1) DEFAULT '0',
    create_by varchar(64) DEFAULT '',
    create_time timestamp DEFAULT NULL,
    update_by varchar(64) DEFAULT '',
    update_time timestamp DEFAULT NULL,
    remark varchar(500) DEFAULT '',
    PRIMARY KEY (job_id,job_name,job_group)
);

CREATE TABLE IF NOT EXISTS sys_job_log (
    job_log_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    job_name varchar(64) NOT NULL,
    job_group varchar(64) NOT NULL,
    invoke_target varchar(500) NOT NULL,
    job_message varchar(500) DEFAULT NULL,
    status char(1) DEFAULT '0',
    exception_info varchar(2000) DEFAULT '',
    create_time timestamp DEFAULT NULL,
    PRIMARY KEY (job_log_id)
);

CREATE TABLE IF NOT EXISTS sys_logininfor (
    info_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_name varchar(50) DEFAULT '',
    ipaddr varchar(128) DEFAULT '',
    login_location varchar(255) DEFAULT '',
    browser varchar(50) DEFAULT '',
    os varchar(50) DEFAULT '',
    status char(1) DEFAULT '0',
    msg varchar(255) DEFAULT '',
    login_time timestamp DEFAULT NULL,
    PRIMARY KEY (info_id)
);

CREATE TABLE IF NOT EXISTS sys_menu (
    menu_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    menu_name varchar(50) NOT NULL,
    parent_id bigint DEFAULT 0,
    order_num int DEFAULT 0,
    path varchar(200) DEFAULT '',
    component varchar(255) DEFAULT NULL,
    query varchar(255) DEFAULT NULL,
    is_frame int DEFAULT 1,
    is_cache int DEFAULT 0,
    menu_type char(1) DEFAULT '',
    visible char(1) DEFAULT '0',
    status char(1) DEFAULT '0',
    perms varchar(100) DEFAULT NULL,
    icon varchar(100) DEFAULT '#',
    create_by varchar(64) DEFAULT '',
    create_time timestamp DEFAULT NULL,
    update_by varchar(64) DEFAULT '',
    update_time timestamp DEFAULT NULL,
    remark varchar(500) DEFAULT '',
    PRIMARY KEY (menu_id)
);

CREATE TABLE IF NOT EXISTS sys_notice (
    notice_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    notice_title varchar(50) NOT NULL,
    notice_type char(1) NOT NULL,
    notice_content bytea,
    status char(1) DEFAULT '0',
    create_by varchar(64) DEFAULT '',
    create_time timestamp DEFAULT NULL,
    update_by varchar(64) DEFAULT '',
    update_time timestamp DEFAULT NULL,
    remark varchar(255) DEFAULT NULL,
    PRIMARY KEY (notice_id)
);

CREATE TABLE IF NOT EXISTS sys_oper_log (
    oper_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    title varchar(50) DEFAULT '',
    business_type int DEFAULT 0,
    method varchar(100) DEFAULT '',
    request_method varchar(10) DEFAULT '',
    operator_type int DEFAULT 0,
    oper_name varchar(50) DEFAULT '',
    dept_name varchar(50) DEFAULT '',
    oper_url varchar(255) DEFAULT '',
    oper_ip varchar(128) DEFAULT '',
    oper_location varchar(255) DEFAULT '',
    oper_param varchar(2000) DEFAULT '',
    json_result varchar(2000) DEFAULT '',
    status int DEFAULT 0,
    error_msg varchar(2000) DEFAULT '',
    oper_time timestamp DEFAULT NULL,
    cost_time bigint DEFAULT 0,
    PRIMARY KEY (oper_id)
);

CREATE TABLE IF NOT EXISTS sys_post (
    post_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    post_code varchar(64) NOT NULL,
    post_name varchar(50) NOT NULL,
    post_sort int NOT NULL,
    status char(1) NOT NULL,
    create_by varchar(64) DEFAULT '',
    create_time timestamp DEFAULT NULL,
    update_by varchar(64) DEFAULT '',
    update_time timestamp DEFAULT NULL,
    remark varchar(500) DEFAULT NULL,
    PRIMARY KEY (post_id)
);

CREATE TABLE IF NOT EXISTS sys_role (
    role_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    role_name varchar(30) NOT NULL,
    role_key varchar(100) NOT NULL,
    role_sort int NOT NULL,
    data_scope char(1) DEFAULT '1',
    menu_check_strictly smallint DEFAULT 1,
    dept_check_strictly smallint DEFAULT 1,
    status char(1) NOT NULL,
    del_flag char(1) DEFAULT '0',
    create_by varchar(64) DEFAULT '',
    create_time timestamp DEFAULT NULL,
    update_by varchar(64) DEFAULT '',
    update_time timestamp DEFAULT NULL,
    remark varchar(500) DEFAULT NULL,
    PRIMARY KEY (role_id)
);

CREATE TABLE IF NOT EXISTS sys_role_dept (
    role_id bigint NOT NULL,
    dept_id bigint NOT NULL,
    PRIMARY KEY (role_id,dept_id)
);

CREATE TABLE IF NOT EXISTS sys_role_menu (
    role_id bigint NOT NULL,
    menu_id bigint NOT NULL,
    PRIMARY KEY (role_id,menu_id)
);

CREATE TABLE IF NOT EXISTS sys_user (
    user_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    dept_id bigint DEFAULT NULL,
    user_name varchar(30) NOT NULL,
    nick_name varchar(30) NOT NULL,
    user_type varchar(2) DEFAULT '00',
    email varchar(50) DEFAULT '',
    phonenumber varchar(11) DEFAULT '',
    sex char(1) DEFAULT '0',
    avatar varchar(100) DEFAULT '',
    password varchar(100) DEFAULT '',
    status char(1) DEFAULT '0',
    del_flag char(1) DEFAULT '0',
    login_ip varchar(128) DEFAULT '',
    login_date timestamp DEFAULT NULL,
    create_by varchar(64) DEFAULT '',
    create_time timestamp DEFAULT NULL,
    update_by varchar(64) DEFAULT '',
    update_time timestamp DEFAULT NULL,
    remark varchar(500) DEFAULT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS sys_user_post (
    user_id bigint NOT NULL,
    post_id bigint NOT NULL,
    PRIMARY KEY (user_id,post_id)
);

CREATE TABLE IF NOT EXISTS sys_user_role (
    user_id bigint NOT NULL,
    role_id bigint NOT NULL,
    PRIMARY KEY (user_id,role_id)
);

CREATE TABLE IF NOT EXISTS tb_channel (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    channel_code varchar(10) NOT NULL,
    sku_id bigint DEFAULT 0,
    vm_id bigint NOT NULL,
    inner_code varchar(15) NOT NULL,
    max_capacity int NOT NULL DEFAULT 0,
    current_capacity int DEFAULT 0,
    last_supply_time timestamp DEFAULT NULL,
    create_time timestamp DEFAULT NULL,
    update_time timestamp DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS tb_emp (
    id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_name varchar(50) NOT NULL,
    region_id integer DEFAULT NULL,
    region_name varchar(50) DEFAULT NULL,
    role_id int DEFAULT NULL,
    role_code varchar(10) DEFAULT NULL,
    role_name varchar(50) DEFAULT NULL,
    mobile varchar(15) DEFAULT NULL,
    image varchar(500) DEFAULT NULL,
    status smallint DEFAULT 1,
    create_time timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS tb_job (
    id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    alert_value int DEFAULT 0,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS tb_node (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    region_id integer DEFAULT NULL,
    partner_id integer DEFAULT NULL,
    node_name varchar(80) NOT NULL DEFAULT '',
    address varchar(200) NOT NULL DEFAULT '',
    business_type int NOT NULL DEFAULT 0,
    create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_by varchar(30) NOT NULL DEFAULT 'admin',
    update_by varchar(30) NOT NULL DEFAULT 'admin',
    remark varchar(255) DEFAULT '',
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS tb_order (
    id bigint NOT NULL,
    order_no varchar(50) NOT NULL,
    third_no varchar(34) DEFAULT NULL,
    inner_code varchar(15) DEFAULT NULL,
    channel_code varchar(10) DEFAULT NULL,
    sku_id bigint DEFAULT NULL,
    sku_name varchar(20) DEFAULT NULL,
    class_id int DEFAULT NULL,
    status int DEFAULT NULL,
    amount int NOT NULL DEFAULT 0,
    price int NOT NULL DEFAULT 0,
    pay_type varchar(10) DEFAULT NULL,
    pay_status int DEFAULT 0,
    bill int DEFAULT 0,
    addr varchar(200) DEFAULT NULL,
    region_id bigint DEFAULT NULL,
    region_name varchar(50) DEFAULT NULL,
    business_type int DEFAULT NULL,
    partner_id int DEFAULT NULL,
    open_id varchar(200) DEFAULT NULL,
    node_id bigint DEFAULT NULL,
    node_name varchar(50) DEFAULT NULL,
    cancel_desc varchar(200) DEFAULT '',
    create_time timestamp NULL DEFAULT NULL,
    update_time timestamp NULL DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS tb_order_collect (
    id bigint NOT NULL,
    partner_id int DEFAULT NULL,
    partner_name varchar(100) DEFAULT NULL,
    order_total_money bigint DEFAULT NULL,
    order_date date DEFAULT NULL,
    total_bill int DEFAULT 0,
    node_id int DEFAULT NULL,
    node_name varchar(50) DEFAULT NULL,
    order_count int DEFAULT NULL,
    ratio int DEFAULT NULL,
    region_name varchar(50) DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS tb_order_month_collect (
    id bigint NOT NULL,
    partner_id int DEFAULT NULL,
    partner_name varchar(100) DEFAULT NULL,
    region_id int DEFAULT NULL,
    region_name varchar(50) DEFAULT NULL,
    order_total_money bigint DEFAULT NULL,
    order_total_count bigint DEFAULT NULL,
    month int DEFAULT NULL,
    year int DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS tb_partner (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    partner_name varchar(80) NOT NULL DEFAULT '',
    contact_person varchar(20) NOT NULL DEFAULT '',
    contact_phone varchar(11) NOT NULL DEFAULT '',
    divide_ratio int NOT NULL DEFAULT 0,
    account varchar(50) NOT NULL DEFAULT '',
    password varchar(100) NOT NULL DEFAULT '',
    create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_by varchar(30) NOT NULL DEFAULT 'admin',
    update_by varchar(30) NOT NULL DEFAULT 'admin',
    remark varchar(255) DEFAULT '',
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS tb_policy (
    policy_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    policy_name varchar(30) DEFAULT NULL,
    discount int DEFAULT NULL,
    create_time timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (policy_id)
);

CREATE TABLE IF NOT EXISTS tb_region (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    region_name varchar(50) NOT NULL DEFAULT '',
    create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_by varchar(30) NOT NULL DEFAULT 'admin',
    update_by varchar(30) NOT NULL DEFAULT 'admin',
    remark varchar(255) DEFAULT '',
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS tb_role (
    role_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    role_code varchar(50) DEFAULT NULL,
    role_name varchar(50) DEFAULT NULL,
    PRIMARY KEY (role_id)
);

CREATE TABLE IF NOT EXISTS tb_sku (
    sku_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    sku_name varchar(50) NOT NULL,
    sku_image varchar(500) NOT NULL,
    brand_Name varchar(50) NOT NULL,
    unit varchar(20) DEFAULT NULL,
    price int NOT NULL DEFAULT 1,
    class_id int NOT NULL,
    is_discount smallint DEFAULT 0,
    create_time timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (sku_id)
);

CREATE TABLE IF NOT EXISTS tb_sku_class (
    class_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    class_name varchar(50) DEFAULT '',
    parent_id int DEFAULT 0,
    PRIMARY KEY (class_id)
);

CREATE TABLE IF NOT EXISTS tb_task (
    task_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    task_code varchar(40) NOT NULL,
    task_status int DEFAULT NULL,
    create_type int DEFAULT NULL,
    inner_code varchar(15) DEFAULT NULL,
    user_id int DEFAULT NULL,
    user_name varchar(50) DEFAULT NULL,
    region_id bigint DEFAULT NULL,
    "desc" varchar(255) DEFAULT NULL,
    product_type_id int DEFAULT 1,
    assignor_id int DEFAULT NULL,
    addr varchar(200) DEFAULT NULL,
    create_time timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (task_id)
);

CREATE TABLE IF NOT EXISTS tb_task_collect (
    id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id int DEFAULT NULL,
    finish_count int DEFAULT 0,
    progress_count int DEFAULT 0,
    cancel_count int DEFAULT 0,
    collect_date date DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS tb_task_details (
    details_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    task_id bigint DEFAULT NULL,
    channel_code varchar(10) DEFAULT NULL,
    expect_capacity int NOT NULL DEFAULT 0,
    sku_id bigint DEFAULT NULL,
    sku_name varchar(50) DEFAULT NULL,
    sku_image varchar(500) DEFAULT NULL,
    PRIMARY KEY (details_id)
);

CREATE TABLE IF NOT EXISTS tb_task_type (
    type_id int NOT NULL,
    type_name varchar(20) DEFAULT NULL,
    type int DEFAULT 1,
    PRIMARY KEY (type_id)
);

CREATE TABLE IF NOT EXISTS tb_vending_machine (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    inner_code varchar(15) DEFAULT '000',
    channel_max_capacity int DEFAULT NULL,
    node_id int NOT NULL,
    addr varchar(100) DEFAULT NULL,
    last_supply_time timestamp NOT NULL DEFAULT '2000-01-01 00:00:00',
    business_type int NOT NULL,
    region_id int NOT NULL,
    partner_id int NOT NULL,
    vm_type_id int NOT NULL DEFAULT 0,
    vm_status int NOT NULL DEFAULT 0,
    running_status varchar(100) DEFAULT NULL,
    longitudes double precision DEFAULT 0,
    latitude double precision DEFAULT 0,
    client_id varchar(50) DEFAULT NULL,
    policy_id bigint DEFAULT NULL,
    create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS tb_vendout_running (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    order_no varchar(38) NOT NULL DEFAULT '',
    inner_code varchar(15) NOT NULL,
    channel_code varchar(10) DEFAULT NULL,
    status char(1) DEFAULT NULL,
    create_time timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS tb_vm_type (
    id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name varchar(15) NOT NULL,
    model varchar(20) DEFAULT NULL,
    image varchar(500) DEFAULT NULL,
    vm_row int NOT NULL DEFAULT 1,
    vm_col int NOT NULL DEFAULT 1,
    channel_max_capacity int DEFAULT 0,
    PRIMARY KEY (id)
);


-- ==================== 2. UNIQUE INDEXES ====================
CREATE UNIQUE INDEX IF NOT EXISTS dict_type ON sys_dict_type (dict_type);
CREATE UNIQUE INDEX IF NOT EXISTS tb_user_Id_uindex ON tb_emp (id);
CREATE UNIQUE INDEX IF NOT EXISTS tb_user_user_name_uindex ON tb_emp (user_name);
CREATE UNIQUE INDEX IF NOT EXISTS tb_user_mobile_uindex ON tb_emp (mobile);
CREATE UNIQUE INDEX IF NOT EXISTS Order_OrderNo_uindex ON tb_order (order_no);
CREATE UNIQUE INDEX IF NOT EXISTS tb_order_collect_id_uindex ON tb_order_collect (id);
CREATE UNIQUE INDEX IF NOT EXISTS tb_order_month_collect_id_uindex ON tb_order_month_collect (id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_account ON tb_partner (account);
CREATE UNIQUE INDEX IF NOT EXISTS tb_policy_policy_name_uindex ON tb_policy (policy_name);
CREATE UNIQUE INDEX IF NOT EXISTS tb_role_role_code_uindex ON tb_role (role_code);
CREATE UNIQUE INDEX IF NOT EXISTS tb_role_role_name_uindex ON tb_role (role_name);
CREATE UNIQUE INDEX IF NOT EXISTS tb_sku_sku_name_uindex ON tb_sku (sku_name);
CREATE UNIQUE INDEX IF NOT EXISTS tb_sku_class_class_name_uindex ON tb_sku_class (class_name);
CREATE UNIQUE INDEX IF NOT EXISTS tb_task_task_code_uindex ON tb_task (task_code);
CREATE UNIQUE INDEX IF NOT EXISTS vendingmachine_VmId_uindex ON tb_vending_machine (inner_code);
CREATE UNIQUE INDEX IF NOT EXISTS tb_vm_type_name_uindex ON tb_vm_type (name);
CREATE UNIQUE INDEX IF NOT EXISTS tb_vm_type_model_uindex ON tb_vm_type (model);

-- ==================== 3. ORDINARY INDEXES ====================
CREATE INDEX IF NOT EXISTS idx_sys_logininfor_s ON sys_logininfor (status);
CREATE INDEX IF NOT EXISTS idx_sys_logininfor_lt ON sys_logininfor (login_time);
CREATE INDEX IF NOT EXISTS idx_sys_oper_log_bt ON sys_oper_log (business_type);
CREATE INDEX IF NOT EXISTS idx_sys_oper_log_s ON sys_oper_log (status);
CREATE INDEX IF NOT EXISTS idx_sys_oper_log_ot ON sys_oper_log (oper_time);
CREATE INDEX IF NOT EXISTS channel_vendingmachine_Id_fk ON tb_channel (vm_id);
CREATE INDEX IF NOT EXISTS tb_channel_inner_code_index ON tb_channel (inner_code);
CREATE INDEX IF NOT EXISTS role_id ON tb_emp (role_id);
CREATE INDEX IF NOT EXISTS region_id ON tb_emp (region_id);
CREATE INDEX IF NOT EXISTS fk_node_partner ON tb_node (partner_id);
CREATE INDEX IF NOT EXISTS fk_node_region ON tb_node (region_id);
CREATE INDEX IF NOT EXISTS sku_sku_class_ClassId_fk ON tb_sku (class_id);
CREATE INDEX IF NOT EXISTS task_productiontype_TypeId_fk ON tb_task (product_type_id);
CREATE INDEX IF NOT EXISTS task_taskstatustype_StatusID_fk ON tb_task (task_status);
CREATE INDEX IF NOT EXISTS task_tasktype_TypeId_fk ON tb_task (create_type);
CREATE INDEX IF NOT EXISTS taskdetails_task_TaskId_fk ON tb_task_details (task_id);

-- ==================== 4. FOREIGN KEYS ====================
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        JOIN pg_namespace n ON n.oid = t.relnamespace
        WHERE c.conname = 'tb_channel_ibfk_1'
          AND t.relname = 'tb_channel'
          AND n.nspname = current_schema()
    ) THEN
        ALTER TABLE tb_channel ADD CONSTRAINT tb_channel_ibfk_1 FOREIGN KEY (vm_id) REFERENCES tb_vending_machine (id);
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        JOIN pg_namespace n ON n.oid = t.relnamespace
        WHERE c.conname = 'tb_emp_ibfk_1'
          AND t.relname = 'tb_emp'
          AND n.nspname = current_schema()
    ) THEN
        ALTER TABLE tb_emp ADD CONSTRAINT tb_emp_ibfk_1 FOREIGN KEY (role_id) REFERENCES tb_role (role_id);
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        JOIN pg_namespace n ON n.oid = t.relnamespace
        WHERE c.conname = 'tb_emp_ibfk_2'
          AND t.relname = 'tb_emp'
          AND n.nspname = current_schema()
    ) THEN
        ALTER TABLE tb_emp ADD CONSTRAINT tb_emp_ibfk_2 FOREIGN KEY (region_id) REFERENCES tb_region (id);
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        JOIN pg_namespace n ON n.oid = t.relnamespace
        WHERE c.conname = 'fk_node_partner'
          AND t.relname = 'tb_node'
          AND n.nspname = current_schema()
    ) THEN
        ALTER TABLE tb_node ADD CONSTRAINT fk_node_partner FOREIGN KEY (partner_id) REFERENCES tb_partner (id);
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        JOIN pg_namespace n ON n.oid = t.relnamespace
        WHERE c.conname = 'fk_node_region'
          AND t.relname = 'tb_node'
          AND n.nspname = current_schema()
    ) THEN
        ALTER TABLE tb_node ADD CONSTRAINT fk_node_region FOREIGN KEY (region_id) REFERENCES tb_region (id);
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        JOIN pg_namespace n ON n.oid = t.relnamespace
        WHERE c.conname = 'tb_sku_ibfk_1'
          AND t.relname = 'tb_sku'
          AND n.nspname = current_schema()
    ) THEN
        ALTER TABLE tb_sku ADD CONSTRAINT tb_sku_ibfk_1 FOREIGN KEY (class_id) REFERENCES tb_sku_class (class_id);
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        JOIN pg_namespace n ON n.oid = t.relnamespace
        WHERE c.conname = 'taskdetails_task_TaskId_fk'
          AND t.relname = 'tb_task_details'
          AND n.nspname = current_schema()
    ) THEN
        ALTER TABLE tb_task_details ADD CONSTRAINT taskdetails_task_TaskId_fk FOREIGN KEY (task_id) REFERENCES tb_task (task_id);
    END IF;
END $$;

-- ==================== 5. COMMENTS ====================
COMMENT ON TABLE gen_table IS '代码生成业务表';
COMMENT ON TABLE gen_table_column IS '代码生成业务表字段';
COMMENT ON TABLE sys_config IS '参数配置表';
COMMENT ON TABLE sys_dept IS '部门表';
COMMENT ON TABLE sys_dict_data IS '字典数据表';
COMMENT ON TABLE sys_dict_type IS '字典类型表';
COMMENT ON TABLE sys_job IS '定时任务调度表';
COMMENT ON TABLE sys_job_log IS '定时任务调度日志表';
COMMENT ON TABLE sys_logininfor IS '系统访问记录';
COMMENT ON TABLE sys_menu IS '菜单权限表';
COMMENT ON TABLE sys_notice IS '通知公告表';
COMMENT ON TABLE sys_oper_log IS '操作日志记录';
COMMENT ON TABLE sys_post IS '岗位信息表';
COMMENT ON TABLE sys_role IS '角色信息表';
COMMENT ON TABLE sys_role_dept IS '角色和部门关联表';
COMMENT ON TABLE sys_role_menu IS '角色和菜单关联表';
COMMENT ON TABLE sys_user IS '用户信息表';
COMMENT ON TABLE sys_user_post IS '用户与岗位关联表';
COMMENT ON TABLE sys_user_role IS '用户和角色关联表';
COMMENT ON TABLE tb_channel IS '售货机货道表';
COMMENT ON TABLE tb_emp IS '工单员工表';
COMMENT ON TABLE tb_job IS '自动补货任务';
COMMENT ON TABLE tb_node IS '线下广告点位信息表';
COMMENT ON TABLE tb_order IS '订单表';
COMMENT ON TABLE tb_order_collect IS '合作商订单汇总表';
COMMENT ON TABLE tb_order_month_collect IS '按月统计各公司销售情况表';
COMMENT ON TABLE tb_partner IS '广告合作商信息表';
COMMENT ON TABLE tb_policy IS '策略表';
COMMENT ON TABLE tb_region IS '城市区域信息表';
COMMENT ON TABLE tb_role IS '工单角色表';
COMMENT ON TABLE tb_sku IS '商品表';
COMMENT ON TABLE tb_sku_class IS '商品类型表';
COMMENT ON TABLE tb_task IS '工单表';
COMMENT ON TABLE tb_task_collect IS '工单按日统计表';
COMMENT ON TABLE tb_task_details IS '工单详情，只有补货工单才有';
COMMENT ON TABLE tb_task_type IS '工单类型';
COMMENT ON TABLE tb_vending_machine IS '设备表';
COMMENT ON TABLE tb_vendout_running IS '出货流水';
COMMENT ON TABLE tb_vm_type IS '设备类型表';
COMMENT ON COLUMN gen_table.table_id IS '编号';
COMMENT ON COLUMN gen_table.table_name IS '表名称';
COMMENT ON COLUMN gen_table.table_comment IS '表描述';
COMMENT ON COLUMN gen_table.sub_table_name IS '关联子表的表名';
COMMENT ON COLUMN gen_table.sub_table_fk_name IS '子表关联的外键名';
COMMENT ON COLUMN gen_table.class_name IS '实体类名称';
COMMENT ON COLUMN gen_table.tpl_category IS '使用的模板（crud单表操作 tree树表操作）';
COMMENT ON COLUMN gen_table.tpl_web_type IS '前端模板类型（element-ui模版 element-plus模版）';
COMMENT ON COLUMN gen_table.package_name IS '生成包路径';
COMMENT ON COLUMN gen_table.module_name IS '生成模块名';
COMMENT ON COLUMN gen_table.business_name IS '生成业务名';
COMMENT ON COLUMN gen_table.function_name IS '生成功能名';
COMMENT ON COLUMN gen_table.function_author IS '生成功能作者';
COMMENT ON COLUMN gen_table.gen_type IS '生成代码方式（0zip压缩包 1自定义路径）';
COMMENT ON COLUMN gen_table.gen_path IS '生成路径（不填默认项目路径）';
COMMENT ON COLUMN gen_table.options IS '其它生成选项';
COMMENT ON COLUMN gen_table.create_by IS '创建者';
COMMENT ON COLUMN gen_table.create_time IS '创建时间';
COMMENT ON COLUMN gen_table.update_by IS '更新者';
COMMENT ON COLUMN gen_table.update_time IS '更新时间';
COMMENT ON COLUMN gen_table.remark IS '备注';
COMMENT ON COLUMN gen_table_column.column_id IS '编号';
COMMENT ON COLUMN gen_table_column.table_id IS '归属表编号';
COMMENT ON COLUMN gen_table_column.column_name IS '列名称';
COMMENT ON COLUMN gen_table_column.column_comment IS '列描述';
COMMENT ON COLUMN gen_table_column.column_type IS '列类型';
COMMENT ON COLUMN gen_table_column.java_type IS 'JAVA类型';
COMMENT ON COLUMN gen_table_column.java_field IS 'JAVA字段名';
COMMENT ON COLUMN gen_table_column.is_pk IS '是否主键（1是）';
COMMENT ON COLUMN gen_table_column.is_increment IS '是否自增（1是）';
COMMENT ON COLUMN gen_table_column.is_required IS '是否必填（1是）';
COMMENT ON COLUMN gen_table_column.is_insert IS '是否为插入字段（1是）';
COMMENT ON COLUMN gen_table_column.is_edit IS '是否编辑字段（1是）';
COMMENT ON COLUMN gen_table_column.is_list IS '是否列表字段（1是）';
COMMENT ON COLUMN gen_table_column.is_query IS '是否查询字段（1是）';
COMMENT ON COLUMN gen_table_column.query_type IS '查询方式（等于、不等于、大于、小于、范围）';
COMMENT ON COLUMN gen_table_column.html_type IS '显示类型（文本框、文本域、下拉框、复选框、单选框、日期控件）';
COMMENT ON COLUMN gen_table_column.dict_type IS '字典类型';
COMMENT ON COLUMN gen_table_column.sort IS '排序';
COMMENT ON COLUMN gen_table_column.create_by IS '创建者';
COMMENT ON COLUMN gen_table_column.create_time IS '创建时间';
COMMENT ON COLUMN gen_table_column.update_by IS '更新者';
COMMENT ON COLUMN gen_table_column.update_time IS '更新时间';
COMMENT ON COLUMN sys_config.config_id IS '参数主键';
COMMENT ON COLUMN sys_config.config_name IS '参数名称';
COMMENT ON COLUMN sys_config.config_key IS '参数键名';
COMMENT ON COLUMN sys_config.config_value IS '参数键值';
COMMENT ON COLUMN sys_config.config_type IS '系统内置（Y是 N否）';
COMMENT ON COLUMN sys_config.create_by IS '创建者';
COMMENT ON COLUMN sys_config.create_time IS '创建时间';
COMMENT ON COLUMN sys_config.update_by IS '更新者';
COMMENT ON COLUMN sys_config.update_time IS '更新时间';
COMMENT ON COLUMN sys_config.remark IS '备注';
COMMENT ON COLUMN sys_dept.dept_id IS '部门id';
COMMENT ON COLUMN sys_dept.parent_id IS '父部门id';
COMMENT ON COLUMN sys_dept.ancestors IS '祖级列表';
COMMENT ON COLUMN sys_dept.dept_name IS '部门名称';
COMMENT ON COLUMN sys_dept.order_num IS '显示顺序';
COMMENT ON COLUMN sys_dept.leader IS '负责人';
COMMENT ON COLUMN sys_dept.phone IS '联系电话';
COMMENT ON COLUMN sys_dept.email IS '邮箱';
COMMENT ON COLUMN sys_dept.status IS '部门状态（0正常 1停用）';
COMMENT ON COLUMN sys_dept.del_flag IS '删除标志（0代表存在 2代表删除）';
COMMENT ON COLUMN sys_dept.create_by IS '创建者';
COMMENT ON COLUMN sys_dept.create_time IS '创建时间';
COMMENT ON COLUMN sys_dept.update_by IS '更新者';
COMMENT ON COLUMN sys_dept.update_time IS '更新时间';
COMMENT ON COLUMN sys_dict_data.dict_code IS '字典编码';
COMMENT ON COLUMN sys_dict_data.dict_sort IS '字典排序';
COMMENT ON COLUMN sys_dict_data.dict_label IS '字典标签';
COMMENT ON COLUMN sys_dict_data.dict_value IS '字典键值';
COMMENT ON COLUMN sys_dict_data.dict_type IS '字典类型';
COMMENT ON COLUMN sys_dict_data.css_class IS '样式属性（其他样式扩展）';
COMMENT ON COLUMN sys_dict_data.list_class IS '表格回显样式';
COMMENT ON COLUMN sys_dict_data.is_default IS '是否默认（Y是 N否）';
COMMENT ON COLUMN sys_dict_data.status IS '状态（0正常 1停用）';
COMMENT ON COLUMN sys_dict_data.create_by IS '创建者';
COMMENT ON COLUMN sys_dict_data.create_time IS '创建时间';
COMMENT ON COLUMN sys_dict_data.update_by IS '更新者';
COMMENT ON COLUMN sys_dict_data.update_time IS '更新时间';
COMMENT ON COLUMN sys_dict_data.remark IS '备注';
COMMENT ON COLUMN sys_dict_type.dict_id IS '字典主键';
COMMENT ON COLUMN sys_dict_type.dict_name IS '字典名称';
COMMENT ON COLUMN sys_dict_type.dict_type IS '字典类型';
COMMENT ON COLUMN sys_dict_type.status IS '状态（0正常 1停用）';
COMMENT ON COLUMN sys_dict_type.create_by IS '创建者';
COMMENT ON COLUMN sys_dict_type.create_time IS '创建时间';
COMMENT ON COLUMN sys_dict_type.update_by IS '更新者';
COMMENT ON COLUMN sys_dict_type.update_time IS '更新时间';
COMMENT ON COLUMN sys_dict_type.remark IS '备注';
COMMENT ON COLUMN sys_job.job_id IS '任务ID';
COMMENT ON COLUMN sys_job.job_name IS '任务名称';
COMMENT ON COLUMN sys_job.job_group IS '任务组名';
COMMENT ON COLUMN sys_job.invoke_target IS '调用目标字符串';
COMMENT ON COLUMN sys_job.cron_expression IS 'cron执行表达式';
COMMENT ON COLUMN sys_job.misfire_policy IS '计划执行错误策略（1立即执行 2执行一次 3放弃执行）';
COMMENT ON COLUMN sys_job.concurrent IS '是否并发执行（0允许 1禁止）';
COMMENT ON COLUMN sys_job.status IS '状态（0正常 1暂停）';
COMMENT ON COLUMN sys_job.create_by IS '创建者';
COMMENT ON COLUMN sys_job.create_time IS '创建时间';
COMMENT ON COLUMN sys_job.update_by IS '更新者';
COMMENT ON COLUMN sys_job.update_time IS '更新时间';
COMMENT ON COLUMN sys_job.remark IS '备注信息';
COMMENT ON COLUMN sys_job_log.job_log_id IS '任务日志ID';
COMMENT ON COLUMN sys_job_log.job_name IS '任务名称';
COMMENT ON COLUMN sys_job_log.job_group IS '任务组名';
COMMENT ON COLUMN sys_job_log.invoke_target IS '调用目标字符串';
COMMENT ON COLUMN sys_job_log.job_message IS '日志信息';
COMMENT ON COLUMN sys_job_log.status IS '执行状态（0正常 1失败）';
COMMENT ON COLUMN sys_job_log.exception_info IS '异常信息';
COMMENT ON COLUMN sys_job_log.create_time IS '创建时间';
COMMENT ON COLUMN sys_logininfor.info_id IS '访问ID';
COMMENT ON COLUMN sys_logininfor.user_name IS '用户账号';
COMMENT ON COLUMN sys_logininfor.ipaddr IS '登录IP地址';
COMMENT ON COLUMN sys_logininfor.login_location IS '登录地点';
COMMENT ON COLUMN sys_logininfor.browser IS '浏览器类型';
COMMENT ON COLUMN sys_logininfor.os IS '操作系统';
COMMENT ON COLUMN sys_logininfor.status IS '登录状态（0成功 1失败）';
COMMENT ON COLUMN sys_logininfor.msg IS '提示消息';
COMMENT ON COLUMN sys_logininfor.login_time IS '访问时间';
COMMENT ON COLUMN sys_menu.menu_id IS '菜单ID';
COMMENT ON COLUMN sys_menu.menu_name IS '菜单名称';
COMMENT ON COLUMN sys_menu.parent_id IS '父菜单ID';
COMMENT ON COLUMN sys_menu.order_num IS '显示顺序';
COMMENT ON COLUMN sys_menu.path IS '路由地址';
COMMENT ON COLUMN sys_menu.component IS '组件路径';
COMMENT ON COLUMN sys_menu.query IS '路由参数';
COMMENT ON COLUMN sys_menu.is_frame IS '是否为外链（0是 1否）';
COMMENT ON COLUMN sys_menu.is_cache IS '是否缓存（0缓存 1不缓存）';
COMMENT ON COLUMN sys_menu.menu_type IS '菜单类型（M目录 C菜单 F按钮）';
COMMENT ON COLUMN sys_menu.visible IS '菜单状态（0显示 1隐藏）';
COMMENT ON COLUMN sys_menu.status IS '菜单状态（0正常 1停用）';
COMMENT ON COLUMN sys_menu.perms IS '权限标识';
COMMENT ON COLUMN sys_menu.icon IS '菜单图标';
COMMENT ON COLUMN sys_menu.create_by IS '创建者';
COMMENT ON COLUMN sys_menu.create_time IS '创建时间';
COMMENT ON COLUMN sys_menu.update_by IS '更新者';
COMMENT ON COLUMN sys_menu.update_time IS '更新时间';
COMMENT ON COLUMN sys_menu.remark IS '备注';
COMMENT ON COLUMN sys_notice.notice_id IS '公告ID';
COMMENT ON COLUMN sys_notice.notice_title IS '公告标题';
COMMENT ON COLUMN sys_notice.notice_type IS '公告类型（1通知 2公告）';
COMMENT ON COLUMN sys_notice.notice_content IS '公告内容';
COMMENT ON COLUMN sys_notice.status IS '公告状态（0正常 1关闭）';
COMMENT ON COLUMN sys_notice.create_by IS '创建者';
COMMENT ON COLUMN sys_notice.create_time IS '创建时间';
COMMENT ON COLUMN sys_notice.update_by IS '更新者';
COMMENT ON COLUMN sys_notice.update_time IS '更新时间';
COMMENT ON COLUMN sys_notice.remark IS '备注';
COMMENT ON COLUMN sys_oper_log.oper_id IS '日志主键';
COMMENT ON COLUMN sys_oper_log.title IS '模块标题';
COMMENT ON COLUMN sys_oper_log.business_type IS '业务类型（0其它 1新增 2修改 3删除）';
COMMENT ON COLUMN sys_oper_log.method IS '方法名称';
COMMENT ON COLUMN sys_oper_log.request_method IS '请求方式';
COMMENT ON COLUMN sys_oper_log.operator_type IS '操作类别（0其它 1后台用户 2手机端用户）';
COMMENT ON COLUMN sys_oper_log.oper_name IS '操作人员';
COMMENT ON COLUMN sys_oper_log.dept_name IS '部门名称';
COMMENT ON COLUMN sys_oper_log.oper_url IS '请求URL';
COMMENT ON COLUMN sys_oper_log.oper_ip IS '主机地址';
COMMENT ON COLUMN sys_oper_log.oper_location IS '操作地点';
COMMENT ON COLUMN sys_oper_log.oper_param IS '请求参数';
COMMENT ON COLUMN sys_oper_log.json_result IS '返回参数';
COMMENT ON COLUMN sys_oper_log.status IS '操作状态（0正常 1异常）';
COMMENT ON COLUMN sys_oper_log.error_msg IS '错误消息';
COMMENT ON COLUMN sys_oper_log.oper_time IS '操作时间';
COMMENT ON COLUMN sys_oper_log.cost_time IS '消耗时间';
COMMENT ON COLUMN sys_post.post_id IS '岗位ID';
COMMENT ON COLUMN sys_post.post_code IS '岗位编码';
COMMENT ON COLUMN sys_post.post_name IS '岗位名称';
COMMENT ON COLUMN sys_post.post_sort IS '显示顺序';
COMMENT ON COLUMN sys_post.status IS '状态（0正常 1停用）';
COMMENT ON COLUMN sys_post.create_by IS '创建者';
COMMENT ON COLUMN sys_post.create_time IS '创建时间';
COMMENT ON COLUMN sys_post.update_by IS '更新者';
COMMENT ON COLUMN sys_post.update_time IS '更新时间';
COMMENT ON COLUMN sys_post.remark IS '备注';
COMMENT ON COLUMN sys_role.role_id IS '角色ID';
COMMENT ON COLUMN sys_role.role_name IS '角色名称';
COMMENT ON COLUMN sys_role.role_key IS '角色权限字符串';
COMMENT ON COLUMN sys_role.role_sort IS '显示顺序';
COMMENT ON COLUMN sys_role.data_scope IS '数据范围（1：全部数据权限 2：自定数据权限 3：本部门数据权限 4：本部门及以下数据权限）';
COMMENT ON COLUMN sys_role.menu_check_strictly IS '菜单树选择项是否关联显示';
COMMENT ON COLUMN sys_role.dept_check_strictly IS '部门树选择项是否关联显示';
COMMENT ON COLUMN sys_role.status IS '角色状态（0正常 1停用）';
COMMENT ON COLUMN sys_role.del_flag IS '删除标志（0代表存在 2代表删除）';
COMMENT ON COLUMN sys_role.create_by IS '创建者';
COMMENT ON COLUMN sys_role.create_time IS '创建时间';
COMMENT ON COLUMN sys_role.update_by IS '更新者';
COMMENT ON COLUMN sys_role.update_time IS '更新时间';
COMMENT ON COLUMN sys_role.remark IS '备注';
COMMENT ON COLUMN sys_role_dept.role_id IS '角色ID';
COMMENT ON COLUMN sys_role_dept.dept_id IS '部门ID';
COMMENT ON COLUMN sys_role_menu.role_id IS '角色ID';
COMMENT ON COLUMN sys_role_menu.menu_id IS '菜单ID';
COMMENT ON COLUMN sys_user.user_id IS '用户ID';
COMMENT ON COLUMN sys_user.dept_id IS '部门ID';
COMMENT ON COLUMN sys_user.user_name IS '用户账号';
COMMENT ON COLUMN sys_user.nick_name IS '用户昵称';
COMMENT ON COLUMN sys_user.user_type IS '用户类型（00系统用户）';
COMMENT ON COLUMN sys_user.email IS '用户邮箱';
COMMENT ON COLUMN sys_user.phonenumber IS '手机号码';
COMMENT ON COLUMN sys_user.sex IS '用户性别（0男 1女 2未知）';
COMMENT ON COLUMN sys_user.avatar IS '头像地址';
COMMENT ON COLUMN sys_user.password IS '密码';
COMMENT ON COLUMN sys_user.status IS '帐号状态（0正常 1停用）';
COMMENT ON COLUMN sys_user.del_flag IS '删除标志（0代表存在 2代表删除）';
COMMENT ON COLUMN sys_user.login_ip IS '最后登录IP';
COMMENT ON COLUMN sys_user.login_date IS '最后登录时间';
COMMENT ON COLUMN sys_user.create_by IS '创建者';
COMMENT ON COLUMN sys_user.create_time IS '创建时间';
COMMENT ON COLUMN sys_user.update_by IS '更新者';
COMMENT ON COLUMN sys_user.update_time IS '更新时间';
COMMENT ON COLUMN sys_user.remark IS '备注';
COMMENT ON COLUMN sys_user_post.user_id IS '用户ID';
COMMENT ON COLUMN sys_user_post.post_id IS '岗位ID';
COMMENT ON COLUMN sys_user_role.user_id IS '用户ID';
COMMENT ON COLUMN sys_user_role.role_id IS '角色ID';
COMMENT ON COLUMN tb_channel.id IS '主键';
COMMENT ON COLUMN tb_channel.channel_code IS '货道编号';
COMMENT ON COLUMN tb_channel.sku_id IS '商品Id';
COMMENT ON COLUMN tb_channel.vm_id IS '售货机Id';
COMMENT ON COLUMN tb_channel.inner_code IS '售货机软编号';
COMMENT ON COLUMN tb_channel.max_capacity IS '货道最大容量';
COMMENT ON COLUMN tb_channel.current_capacity IS '货道当前容量';
COMMENT ON COLUMN tb_channel.last_supply_time IS '上次补货时间';
COMMENT ON COLUMN tb_channel.create_time IS '创建时间';
COMMENT ON COLUMN tb_channel.update_time IS '修改时间';
COMMENT ON COLUMN tb_emp.id IS '主键';
COMMENT ON COLUMN tb_emp.user_name IS '员工名称';
COMMENT ON COLUMN tb_emp.region_id IS '所属区域Id';
COMMENT ON COLUMN tb_emp.region_name IS '区域名称';
COMMENT ON COLUMN tb_emp.role_id IS '角色id';
COMMENT ON COLUMN tb_emp.role_code IS '角色编号';
COMMENT ON COLUMN tb_emp.role_name IS '角色名称';
COMMENT ON COLUMN tb_emp.mobile IS '联系电话';
COMMENT ON COLUMN tb_emp.image IS '员工头像';
COMMENT ON COLUMN tb_emp.status IS '是否启用';
COMMENT ON COLUMN tb_emp.create_time IS '创建时间';
COMMENT ON COLUMN tb_emp.update_time IS '修改时间';
COMMENT ON COLUMN tb_job.id IS '主键';
COMMENT ON COLUMN tb_job.alert_value IS '警戒值百分比';
COMMENT ON COLUMN tb_node.id IS '点位主键ID';
COMMENT ON COLUMN tb_node.region_id IS '所属区域ID，关联tb_region.id';
COMMENT ON COLUMN tb_node.partner_id IS '所属合作商ID，关联tb_partner.id';
COMMENT ON COLUMN tb_node.node_name IS '点位名称';
COMMENT ON COLUMN tb_node.address IS '详细地址';
COMMENT ON COLUMN tb_node.business_type IS '商圈类型：1商务CBD 2潮流购物中心 3社区商业 4文旅步行街';
COMMENT ON COLUMN tb_node.create_time IS '创建时间';
COMMENT ON COLUMN tb_node.update_time IS '修改时间';
COMMENT ON COLUMN tb_node.create_by IS '创建人账号';
COMMENT ON COLUMN tb_node.update_by IS '修改人账号';
COMMENT ON COLUMN tb_node.remark IS '备注信息';
COMMENT ON COLUMN tb_order.id IS '主键';
COMMENT ON COLUMN tb_order.order_no IS '订单编号';
COMMENT ON COLUMN tb_order.third_no IS '第三方平台单号';
COMMENT ON COLUMN tb_order.inner_code IS '机器编号';
COMMENT ON COLUMN tb_order.channel_code IS '货道编号';
COMMENT ON COLUMN tb_order.sku_id IS 'skuId';
COMMENT ON COLUMN tb_order.sku_name IS '商品名称';
COMMENT ON COLUMN tb_order.class_id IS '商品类别Id';
COMMENT ON COLUMN tb_order.status IS '订单状态:0-待支付;1-支付完成;2-出货成功;3-出货失败;4-已取消';
COMMENT ON COLUMN tb_order.amount IS '支付金额';
COMMENT ON COLUMN tb_order.price IS '商品金额';
COMMENT ON COLUMN tb_order.pay_type IS '支付类型，1支付宝 2微信';
COMMENT ON COLUMN tb_order.pay_status IS '支付状态，0-未支付;1-支付完成;2-退款中;3-退款完成';
COMMENT ON COLUMN tb_order.bill IS '合作商账单金额';
COMMENT ON COLUMN tb_order.addr IS '点位地址';
COMMENT ON COLUMN tb_order.region_id IS '所属区域Id';
COMMENT ON COLUMN tb_order.region_name IS '区域名称';
COMMENT ON COLUMN tb_order.business_type IS '所属商圈';
COMMENT ON COLUMN tb_order.partner_id IS '合作商Id';
COMMENT ON COLUMN tb_order.open_id IS '跨站身份验证';
COMMENT ON COLUMN tb_order.node_id IS '点位Id';
COMMENT ON COLUMN tb_order.node_name IS '点位名称';
COMMENT ON COLUMN tb_order.cancel_desc IS '取消原因';
COMMENT ON COLUMN tb_order.create_time IS '创建时间';
COMMENT ON COLUMN tb_order.update_time IS '更新时间';
COMMENT ON COLUMN tb_order_collect.id IS 'Id';
COMMENT ON COLUMN tb_order_collect.partner_id IS '合作商Id';
COMMENT ON COLUMN tb_order_collect.partner_name IS '合作商名称';
COMMENT ON COLUMN tb_order_collect.order_total_money IS '日订单收入总金额(平台端总数)';
COMMENT ON COLUMN tb_order_collect.order_date IS '发生日期';
COMMENT ON COLUMN tb_order_collect.total_bill IS '分成总金额';
COMMENT ON COLUMN tb_order_collect.node_name IS '点位';
COMMENT ON COLUMN tb_order_collect.order_count IS '订单数';
COMMENT ON COLUMN tb_order_collect.ratio IS '分成比例';
COMMENT ON COLUMN tb_order_collect.region_name IS '区域名称';
COMMENT ON COLUMN tb_order_month_collect.id IS 'id';
COMMENT ON COLUMN tb_order_month_collect.partner_id IS '合作商Id';
COMMENT ON COLUMN tb_order_month_collect.partner_name IS '合作商名称';
COMMENT ON COLUMN tb_order_month_collect.region_id IS '区域Id';
COMMENT ON COLUMN tb_order_month_collect.region_name IS '地区名称';
COMMENT ON COLUMN tb_order_month_collect.order_total_money IS '订单总金额';
COMMENT ON COLUMN tb_order_month_collect.order_total_count IS '订单总数';
COMMENT ON COLUMN tb_order_month_collect.month IS '月份';
COMMENT ON COLUMN tb_order_month_collect.year IS '年份';
COMMENT ON COLUMN tb_partner.id IS '合作商主键ID';
COMMENT ON COLUMN tb_partner.partner_name IS '合作商名称';
COMMENT ON COLUMN tb_partner.contact_person IS '联系人';
COMMENT ON COLUMN tb_partner.contact_phone IS '联系电话';
COMMENT ON COLUMN tb_partner.divide_ratio IS '分成比例（单位%，整数）';
COMMENT ON COLUMN tb_partner.account IS '登录账号';
COMMENT ON COLUMN tb_partner.password IS '登录密码（加密存储）';
COMMENT ON COLUMN tb_partner.create_time IS '创建时间';
COMMENT ON COLUMN tb_partner.update_time IS '修改时间';
COMMENT ON COLUMN tb_partner.create_by IS '创建人账号';
COMMENT ON COLUMN tb_partner.update_by IS '修改人账号';
COMMENT ON COLUMN tb_partner.remark IS '备注信息';
COMMENT ON COLUMN tb_policy.policy_id IS '策略id';
COMMENT ON COLUMN tb_policy.policy_name IS '策略名称';
COMMENT ON COLUMN tb_policy.discount IS '策略方案，如：80代表8折';
COMMENT ON COLUMN tb_policy.create_time IS '创建时间';
COMMENT ON COLUMN tb_policy.update_time IS '修改时间';
COMMENT ON COLUMN tb_region.id IS '区域主键ID';
COMMENT ON COLUMN tb_region.region_name IS '区域名称';
COMMENT ON COLUMN tb_region.create_time IS '创建时间';
COMMENT ON COLUMN tb_region.update_time IS '修改时间';
COMMENT ON COLUMN tb_region.create_by IS '创建人账号';
COMMENT ON COLUMN tb_region.update_by IS '修改人账号';
COMMENT ON COLUMN tb_region.remark IS '备注信息';
COMMENT ON COLUMN tb_role.role_code IS '角色编码
';
COMMENT ON COLUMN tb_role.role_name IS '角色名称
';
COMMENT ON COLUMN tb_sku.sku_id IS '主键';
COMMENT ON COLUMN tb_sku.sku_name IS '商品名称';
COMMENT ON COLUMN tb_sku.sku_image IS '商品图片';
COMMENT ON COLUMN tb_sku.brand_Name IS '品牌';
COMMENT ON COLUMN tb_sku.unit IS '规格(净含量)';
COMMENT ON COLUMN tb_sku.price IS '商品价格，单位分';
COMMENT ON COLUMN tb_sku.class_id IS '商品类型Id';
COMMENT ON COLUMN tb_sku.is_discount IS '是否打折促销';
COMMENT ON COLUMN tb_sku.create_time IS '创建时间';
COMMENT ON COLUMN tb_sku.update_time IS '修改时间';
COMMENT ON COLUMN tb_sku_class.class_id IS '主键';
COMMENT ON COLUMN tb_sku_class.class_name IS '类别名称';
COMMENT ON COLUMN tb_sku_class.parent_id IS '上级id';
COMMENT ON COLUMN tb_task.task_id IS '工单ID';
COMMENT ON COLUMN tb_task.task_code IS '工单编号';
COMMENT ON COLUMN tb_task.task_status IS '工单状态';
COMMENT ON COLUMN tb_task.create_type IS '创建类型 0：自动 1：手动';
COMMENT ON COLUMN tb_task.inner_code IS '售货机编码';
COMMENT ON COLUMN tb_task.user_id IS '执行人id';
COMMENT ON COLUMN tb_task.user_name IS '执行人名称';
COMMENT ON COLUMN tb_task.region_id IS '所属区域Id';
COMMENT ON COLUMN tb_task.desc IS '备注';
COMMENT ON COLUMN tb_task.product_type_id IS '工单类型id';
COMMENT ON COLUMN tb_task.assignor_id IS '指派人Id';
COMMENT ON COLUMN tb_task.addr IS '地址';
COMMENT ON COLUMN tb_task.create_time IS '创建时间';
COMMENT ON COLUMN tb_task.update_time IS '更新时间';
COMMENT ON COLUMN tb_task_collect.finish_count IS '当日工单完成数';
COMMENT ON COLUMN tb_task_collect.progress_count IS '当日进行中的工单数';
COMMENT ON COLUMN tb_task_collect.cancel_count IS '当日取消工单数';
COMMENT ON COLUMN tb_task_collect.collect_date IS '汇总的日期';
COMMENT ON COLUMN tb_task_details.task_id IS '工单Id';
COMMENT ON COLUMN tb_task_details.channel_code IS '货道编号';
COMMENT ON COLUMN tb_task_details.expect_capacity IS '补货期望容量';
COMMENT ON COLUMN tb_task_details.sku_id IS '商品Id';
COMMENT ON COLUMN tb_task_type.type_name IS '类型名称';
COMMENT ON COLUMN tb_task_type.type IS '工单类型。1:维修工单;2:运营工单';
COMMENT ON COLUMN tb_vending_machine.id IS '主键';
COMMENT ON COLUMN tb_vending_machine.inner_code IS '设备编号';
COMMENT ON COLUMN tb_vending_machine.channel_max_capacity IS '设备容量';
COMMENT ON COLUMN tb_vending_machine.node_id IS '点位Id';
COMMENT ON COLUMN tb_vending_machine.addr IS '详细地址';
COMMENT ON COLUMN tb_vending_machine.last_supply_time IS '上次补货时间';
COMMENT ON COLUMN tb_vending_machine.business_type IS '商圈类型';
COMMENT ON COLUMN tb_vending_machine.region_id IS '区域Id';
COMMENT ON COLUMN tb_vending_machine.partner_id IS '合作商Id';
COMMENT ON COLUMN tb_vending_machine.vm_type_id IS '设备型号';
COMMENT ON COLUMN tb_vending_machine.vm_status IS '设备状态，0:未投放;1-运营;3-撤机';
COMMENT ON COLUMN tb_vending_machine.running_status IS '运行状态';
COMMENT ON COLUMN tb_vending_machine.longitudes IS '经度';
COMMENT ON COLUMN tb_vending_machine.latitude IS '维度';
COMMENT ON COLUMN tb_vending_machine.client_id IS '客户端连接Id,做emq认证用';
COMMENT ON COLUMN tb_vending_machine.policy_id IS '策略id';
COMMENT ON COLUMN tb_vending_machine.create_time IS '创建时间';
COMMENT ON COLUMN tb_vending_machine.update_time IS '修改时间';
COMMENT ON COLUMN tb_vendout_running.id IS 'id';
COMMENT ON COLUMN tb_vendout_running.order_no IS '订单编号';
COMMENT ON COLUMN tb_vendout_running.inner_code IS '售货机编号';
COMMENT ON COLUMN tb_vendout_running.channel_code IS '货道编号';
COMMENT ON COLUMN tb_vendout_running.status IS '状态';
COMMENT ON COLUMN tb_vendout_running.create_time IS '创建时间';
COMMENT ON COLUMN tb_vendout_running.update_time IS '更新时间';
COMMENT ON COLUMN tb_vm_type.id IS '主键';
COMMENT ON COLUMN tb_vm_type.name IS '型号名称';
COMMENT ON COLUMN tb_vm_type.model IS '型号编码';
COMMENT ON COLUMN tb_vm_type.image IS '设备图片';
COMMENT ON COLUMN tb_vm_type.vm_row IS '货道行';
COMMENT ON COLUMN tb_vm_type.vm_col IS '货道列';
COMMENT ON COLUMN tb_vm_type.channel_max_capacity IS '设备容量';

-- ==================== POST-MIGRATION NOTES ====================
-- 1) If existing data with explicit identity IDs is imported later, synchronize
--    identity sequences afterward so newly generated IDs do not collide.
-- 2) RuoYi backend MyBatis SQL and code-generator information_schema queries
--    still need MySQL -> openGauss/PostgreSQL dialect migration.
-- 3) Run the validation queries below after execution:
--
-- SELECT COUNT(*) FROM pg_tables WHERE schemaname = current_schema();
-- SELECT conname, conrelid::regclass FROM pg_constraint WHERE contype = 'f';
-- SELECT indexname, tablename FROM pg_indexes WHERE schemaname = current_schema();

